name: Helm linter

on:
  push:
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - "charts/**"
    types: [ closed ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    name: Lint charts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Helm
      uses: azure/setup-helm@v4
    - name: Lint
      run: |
        helm lint charts/*
