name: Publish charts

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"
    types: [ closed ]
  workflow_dispatch: {}

jobs:
  release_chart:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push Helm charts as OCI
        run: |
          set -e
          for chart in charts/*/; do
            if [ ! -f "$chart/Chart.yaml" ]; then
              echo "Skipping $chart (no Chart.yaml)"
              continue
            fi
            # extract chart name for target repo
            NAME=$(helm show chart "$chart" | awk '/^name:/ {print $2}')
            # package the chart (creates .tgz in cwd)
            helm package "$chart" --destination .
            # find the generated package
            PACKAGE_FILE=$(ls ${NAME}-*.tgz | head -n1)
            if [ -z "$PACKAGE_FILE" ]; then
              echo "Failed to find packaged chart for $NAME"
              exit 1
            fi
            # push chart to OCI repo
            TARGET="oci://ghcr.io/${{ github.repository }}/charts/$NAME"
            echo "Pushing $PACKAGE_FILE to $TARGET"
            helm push "$PACKAGE_FILE" "$TARGET"
          done
